### PR TITLE
feat: github openid-connect aws actions support

### PR DESCRIPTION
**Pull request by Rishang**
## Story

Why did you create this pull request?

Support for github openid connect actions, as it the best and secure was for use aws creds in github actions

## Solves
check process.env for aws creds as session token

What dose this change?

logic to fetch aws creds

## References
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Do you have any references? (eg. MDN, Stackoverflow)

### CODE REVIEW

**Comment by say8425** [comment]
@Rishang Hello, thank you for your PR. Your code test looks failed.
Please check this log. Thanks.
https://github.com/say8425/aws-secrets-manager-actions/runs/5210475713?check_suite_focus=true#step:7:38

**Review by emanuelflp — CHANGES_REQUESTED** [review]
fix: adds default value to region property in tests

**Comment by mrpatrick** [comment]
any word on this?  Would be awesome if this could be merged

**Comment by say8425** [comment]
```
  env:
    SECRET_NAME: 
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    AWS_DEFAULT_REGION: 
    AWS_DEFAULT_OUTPUT: 
```

https://github.com/say8425/aws-secrets-manager-actions/actions/runs/3023204844/jobs/4863274552#step:7:4

Sorry to response, this PR origin from forked repository. So all secrets are empty, and it makes failed test.
But [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) trigger looks can access these environments.
So I will change this trigger later.

Anyway this PR looks working. So I will fix conflict and approve it.

**Review by say8425 — APPROVED** [review]
I pushed to master branch in my mistake 🥲
But it's strange. I turned on the branch protection but push was success 🤔
Any way, this PR was merged in strange way. So I will approve and close this PR.

Thank you for your contributing @Rishang 👍

**Comment by say8425** [comment]
This PR was already merged.

**Pull request closed without merging**
